Rake.application.options.trace_rules = true

SOURCE_FILES = Rake::FileList.new("sources/**/*.md", "sources/**/*.markdown") #do |fl|
#    fl.exclude("~*")
#    fl.exclude(/^scratch\//)
#    fl.exclude do |f|
#        `git ls-files #{f}`.empty?
#    end
#end

load_paths = FileList["mylibs", "yourlibs"]
SOURCE_FILES.pathmap("%X")

OUTPUT_FILES = SOURCE_FILES.pathmap("%{^sources/, outputs/}X.html")

task :default => :html
task :html => SOURCE_FILES.ext(".html")

rule ".html" => ->(f){source_for_html(f)} do |t|
#rule ".html" => ".md" do |t|
    sh "pandoc -o #{t.name} #{t.source}"
end

def source_for_html(html_file)
    SOURCE_FILES.detect{ |f| f.ext('') == html_file.ext('') }
end

